### ISSUE TITLE
At which step to incorporate peacoQC in Spectre R clustering workflow for spectral flow data?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [saeyslab/PeacoQC#14]
Hi there, 

Thank you for the package. 

I have FCS files acquired by the spectral flow Aurora and had been unmixed. 
I then did Time gate, and gated out doublets and dead cells in FlowJo. 
Next I exported these data and performed arcsinh transformation using the Spectre R package. 
Finally, I exported the transformed data as FCS. 

I now want to perform `PeacoQC()` to QC these FCS files before performing batch alignment and clustering. 

1. Would you mind informing me whether I will therefore simply need to skip `RemoveMargins()`, `compensate()` and `transform()` steps?

2. I saw you provided peacoQC guideline for mass cytometry data, but did not find one for Spectral flow data. Is there particular guidelines or tips you had found useful for spectral data?

Thank you for your help.

**Comment by AnneliesEmmaneel** [comment]
Hi @denvercal1234GitHub,
Thank you for using the package.
If you already unmixed and did an arcsinh transformation in the Spectre package, you do not need to repeat this and can just skip these steps before doing PeacoQC.
Unfortunately, the RemoveMargins function does not work well for spectral cytometry data and we will skip this step when we are analyzing spectral data. I still need to check why it is not working.
There are no guidelines for spectral data because it should follow the typical flow cytometry guidelines (aside from the remove_margins issue) but I will note it down to include it in the vignette as well.
Kind regards,
Annelies

**Comment by denvercal1234GitHub** [comment]
Thank you @AnneliesEmmaneel! I will just skip `RemoveMargins()`, `compensate()` and `transform()` steps and go straight to performing `PeacoQC()` for my transformed spectral data.
