### ISSUE TITLE
Extent of usage of time channel

### ISSUE THREAD

**Issue by jacobpwagner** [saeyslab/PeacoQC#7]
HI @AnneliesEmmaneel. I just wanted to verify the extent to which the time channel is used in PeacoQC.

It seems in general that PeacoQC is meant to be tolerant of the time channel itself not being present, correct? That is, if it's missing, it will mean that [plots may be skipped](https://github.com/saeyslab/PeacoQC/blob/2d255c329421726da589f0ca1bd5b003fc81bdc5/R/PeacoQC.R#L675-L684), but the actual QC will be the same, as it fundamentally is relying just on the ordering of events?

It looks like there is a check and warning if the [event order does not agree with the time channel](https://github.com/saeyslab/PeacoQC/blob/2d255c329421726da589f0ca1bd5b003fc81bdc5/R/PeacoQC_helper_functions.R#L622-L628), but no actual re-ordering appears to take place.

Similarly, the [`time_unit`](https://github.com/saeyslab/PeacoQC/blob/2d255c329421726da589f0ca1bd5b003fc81bdc5/R/PeacoQC.R#L570-L572) argument is only used for visualization purposes, correct?

So the fundamental question is, if the time channel is omitted, will the actual results (in terms of of the QC calls on the events, not the plots) be the same as if it were included?

**Comment by AnneliesEmmaneel** [comment]
Hi, 
If you would omit the time channel, the QC would do exactly the same thing as when you include it.
The time channel is only used to built the plot where you can see how many events are being measured over time. If weird things would happen during the measurement, we mostly can identify them nicely on this plot and that is why it is included.
The check to see if the event order does not agree with the time channel is just a check. We encountered a couple of files where the rows were switched for a strange reason. But we give a warning and don't chance anything ourselves to the original data because you never know if it was done intentional or not.
I hope this answered your questions somewhat?
